### ISSUE TITLE
add feature

### ISSUE THREAD

**Issue by atqraxiaa** [WhiteeRabbit/Triton_RAT#1]
can you add keylogger? and also when the pc has restarted or the file has been executed, it will chat in telegram that the pc is online. thanks! btw good rat

**Comment by WhiteeRabbit** [comment]
Thanks for comment! I will definitely add a keylogger in the future . I tried to do what you said in telegram , but it is impossible to do that immediately when opening the exe , the text was written that the file was open,but when you wrote,for example , /start or /help , the bot will display the answer from your command if the pc exe file is running on the target pc , if it is not running, the bot will not work. Again, thanks for your comment!(don't forget to press the star)😊
